### PR TITLE
Working add/remove and update functions!

### PR DESCRIPTION
**Pull request by Linas490**
Added new controller for changing data in the DataBase. Added cancel buttons for easier navigation.

### CODE REVIEW

**Review by Deminalla — CHANGES_REQUESTED** [review]
Add and edit work. Delete works in removing item from database. However, if you try to order the table after removing an item, it will still show the removed item, but trying to edit/delete it will throw an exception since it's not actually in the database. This probably happens because it is still stored in currentExpenses.

- A solution (not an ideal one because it would restart filter) could be to reload the current page after deleting an item with ```NavigationManager.NavigateTo("/monthlyexp", true);```
- A better solution would be to put ChangeDataController's methods inside MonthlyExpController and when deleting, remove the item from currentExpenses as well. Should fix all issues
- Your own solution (Maybe you can find a way to modify currentExpenses from inside ChangeDataController?)

**Review by Deminalla — COMMENTED** [review]
If you delete an item from an already filtered table, it will reset the currentExpenses with all the data from database. For example, if it was showing just groceries, deleting an expense will show groceries, health and just everything on the database. Basically, it un-filters itself which looks buggy.
It would be better to just remove that specific item from currentExpenses

**Comment by JokubasBu** [comment]
If you ADD to an already filtered table, it resets the filter. But I think it's okay ?

**Review by Deminalla — APPROVED** [review]
Seems to work fine

**Pull request merged**
